refactor: commands

diff --git a/src/commands/send_msg.yml b/src/commands/send_msg.yml
--- a/src/commands/send_msg.yml
+++ b/src/commands/send_msg.yml
@@ -22,4 +22,46 @@ steps:
         TELEGRAM_TEXT: <<parameters.text>>
         TELEGRAM_DISABLE_NOTIFICATION: <<parameters.disable_notification>>
       name: Send message
-      command: scripts/send_msg.sh
+      shell: /bin/bash
+      command: |
+        API_URL=${TELEGRAM_API_URL:-"https://api.telegram.org/bot"}
+        CURL_OPTIONS="-s"
+        
+        TEXT="$TELEGRAM_TEXT"
+        TOKEN="$TELEGRAM_TOKEN"
+        CHATS=( $TELEGRAM_CHAT )
+        DISABLE_NOTIFICATION="$TELEGRAM_DISABLE_NOTIFICATION"
+        
+        if [ -z "$TOKEN" ]; then
+          echo "No bot token was given."
+          exit 1
+        fi
+        
+        if [ ${#CHATS[@]} -eq 0 ]; then
+          echo "No chats given."
+          exit 1
+        fi
+        
+        CURL_OPTIONS="$CURL_OPTIONS --form text=<-"
+        [ "$DISABLE_NOTIFICATION" = true ] && CURL_OPTIONS="$CURL_OPTIONS --form-string disable_notification=true"
+        
+        for CHAT_ID in "${CHATS[@]}"; do
+          MY_CURL_OPTIONS="$CURL_OPTIONS --form-string chat_id=$CHAT_ID"
+      
+          response=$(curl $MY_CURL_OPTIONS "$API_URL$TOKEN/sendMessage" <<< "$TEXT")
+          status=$?
+      
+          if [ $status -ne 0 ]; then
+            echo "curl reported an error. Exit code was: $status."
+            echo "Response was: $response"
+            echo "Quitting."
+            exit $status
+          fi
+      
+          if [[ "$response" != '{"ok":true'* ]]; then
+            echo "Telegram reported an error:"
+            echo "$response"
+            echo "Quitting."
+            exit 1
+          fi
+        done      
