[semver:major] send_msg (#2)
* chore: version bump

* fix ci

* fix ci

* fix ci

* fix: script header

* fix: bash script

* fix: remove useless var

* chore: debug log

* fix: curl options

* feat: add log

* fix: command file

* refactor: commands

* fix: command file

* fix: command file

* fix: command file

* fix: yaml format

* fix: yaml format

diff --git a/src/commands/send_msg.yml b/src/commands/send_msg.yml
--- a/src/commands/send_msg.yml
+++ b/src/commands/send_msg.yml
@@ -16,10 +16,43 @@ parameters:
     description: 'disable telegram push-notification'
 steps:
   - run:
-      environment:
-        TELEGRAM_TOKEN: <<parameters.token>>
-        TELEGRAM_CHAT: <<parameters.to>>
-        TELEGRAM_TEXT: <<parameters.text>>
-        TELEGRAM_DISABLE_NOTIFICATION: <<parameters.disable_notification>>
       name: Send message
-      command: <<include(scripts/send_msg.sh)>>
+      shell: /bin/bash
+      command: |
+        CURL_OPTIONS="-s"
+        TEXT="<<parameters.text>>"
+        TOKEN="<<parameters.token>>"
+        CHAT_ID="<<parameters.to>>"
+        DISABLE_NOTIFICATION="<<parameters.disable_notification>>"
+
+        if [ -z "$TOKEN" ]; then
+          echo "No bot token was given."
+          exit 1
+        fi
+
+        if [ -z "$CHAT_ID" ]; then
+          echo "No chat given."
+          exit 1
+        fi
+
+        CURL_OPTIONS="$CURL_OPTIONS --form text=<-"
+        [ "$DISABLE_NOTIFICATION" = true ] && CURL_OPTIONS="$CURL_OPTIONS --form-string disable_notification=true"
+
+        MY_CURL_OPTIONS="$CURL_OPTIONS --form-string chat_id=$CHAT_ID"
+
+        response=$(curl $MY_CURL_OPTIONS "https://api.telegram.org/bot$TOKEN/sendMessage" \<<< "$TEXT")
+        status=$?
+
+        if [ $status -ne 0 ]; then
+          echo "curl reported an error. Exit code was: $status."
+          echo "Response was: $response"
+          echo "Quitting."
+          exit $status
+        fi
+
+        if [[ "$response" != '{"ok":true'* ]]; then
+          echo "Telegram reported an error:"
+          echo "$response"
+          echo "Quitting."
+          exit 1
+        fi
